USE DATABASE NHS_TARIFF_DEV;
USE SCHEMA NHS_TARIFF_DEV.BRONZE;

CREATE FILE FORMAT IF NOT EXISTS csv_org_format
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY='"';

CREATE FILE FORMAT IF NOT EXISTS txt_icd10_format
  TYPE = CSV
  FIELD_DELIMITER = '\t'  -- tab-separated
  SKIP_HEADER = 1;

CREATE FILE FORMAT IF NOT EXISTS txt_opcs_format
  TYPE = CSV
  FIELD_DELIMITER = '\t';  -- tab-separated